baseURL: "https://jdnmiguel.github.io" 
title: Jérémy Do Nascimento Miguel
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Ongoing work
          url: /working/
          weight: 2
        - name: Teaching
          url: /courses/
          weight: 3
    
params:
    description: "This website hosts Jérémy Do Nascimento Miguel's research papers, course material, curriculum vitae, and contact information."
    author: Jérémy Do Nascimento Miguel
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jérémy Do Nascimento Miguel
          subtitle: " I am a Ph.D. student in Economics at Bordeaux School of Economics (Univ. Bordeaux). **I will defend in October 2024.** My research focuses on agricultural transformation, agricultural value-chain, and social protection in East Africa. I was a Fulbright visiting scholar at UC - Berkeley in 2022-2023, and at the University of Georgia in fall 2021."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jérémy Do Nascimento Miguel
          buttons:
            - name: Research
              url: /papers/
            - name: Ongoing projects
              url: /working/
            - name: Teaching
              url: /courses/
    
    socialIcons:
        - name: CV
          url: /jdnm_cv.pdf
        - name: Email
          url: mailto:jdnmiguel@u-bordeaux.fr
        - name: Location
          url: /location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=bF2SPvAAAAAJ&hl=en&oi=ao
        - name: GitHub
          url: https://github.com/jdnmiguel
        - name: Orcid
          url: https://orcid.org/0000-0002-6275-388X
        - name: X 
          url : https://x.com/j_donami?lang=en
        - name: Linkedin
          url : https://www.linkedin.com/in/jérémy-do-nascimento-miguel-08626a2a6/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Jérémy Do Nascimento Miguel"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
